language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.6

services:
  - postgresql
  - neo4j

before_script:
  - psql -c 'create database thunderbit;' -U postgres

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
 -  find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm