# Server
permalink:        pretty

baseurl:          /thunderbit

exclude:          [.gitignore,README.md]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

name: Thunderbit
description: A web application for digital assets management
url: http://thunderbit.github.io/thunderbit

gems:
  - jemoji