# Server
permalink:        pretty

baseurl:          /thunderbit

exclude:          [.gitignore,README.md]

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
